config/routes.rb
Rails.application.routes.draw do
  get 'questions/new'

  get 'questions/create'

  root 'users#index'

  devise_for :users

  # в профиле юзера показываем его игры, на главной - список лучших игроков
  resources :users, only: [:index, :show]

  resources :games, only: [:create, :show] do
    put 'answer', on: :member # доп. метод ресурса - ответ на текущий вопро
    put 'take_money', on: :member # доп. метод ресурса - игрок берет деньги
    put 'help', on: :member
  end

  resource :questions, only: [:new, :create]
end

app/models/game.rb
#  (c) goodprogrammer.ru
#
# Модельи игры — создается когда пользователь начинает новую игру. Хранит и
# обновляет состояние игры и отвечает за игровой процесс.
class Game < ActiveRecord::Base
  # Сначала несколько констант, задающих механику игры: денежные призы за каждый
  # вопрос, номера несгораемых уровней и временной лимит на одну игру.
  PRIZES = [100, 200, 300, 500, 1_000, 2_000, 4_000, 8_000, 16_000,
            32_000, 64_000, 125_000, 250_000, 500_000, 1_000_000].freeze
  FIREPROOF_LEVELS = [4, 9, 14].freeze
  TIME_LIMIT = 35.minutes

  # У игры есть игрок — пользователь, который начал эту игру
  belongs_to :user

  # Массив игровых вопросов для этой игры. 15 вопросов для 15-ти уровней, в
  # каждый из них мы будем брать произвольный вопрос из общей базы вопросов.
  has_many :game_questions, dependent: :destroy

  # У игры обязательно должен быть игрок
  validates :user, presence: true

  # Текущий уровень сложности вопроса: число от 0 до 14, это поле не можеть быть
  # nil.
  validates :current_level, numericality: {only_integer: true}, allow_nil: false

  # Выигрыш игрока — целое число, лежащее от нуля до максимального приза за игру
  validates :prize, presence: true, numericality: {
    greater_than_or_equal_to: 0, less_than_or_equal_to: PRIZES.last
  }

  # Scope — это метод класса, который возвращает из базы подмножество игр,
  # удовлетворяющих условию. В нашем случае, у которых поле finished_at пусто.
  #
  # http://guides.rubyonrails.org/active_record_querying.html#scopes
  scope :in_progress, -> { where(finished_at: nil) }

  # Фабрика - генератор новой игры
  def self.create_game_for_user!(user)
    # Обратите внимание, что все действия мы делаем единой транзакцией, если
    # где-то словим исключение, откатятся все изменения в базе.
    transaction do
      # Создаем игру для данного игрока
      game = create!(user: user)

      # Созданной игре добавляем ровно 15 новых игровых вопросов разного уровня
      Question::QUESTION_LEVELS.each do |level|
        # Достаем из базы один произвольный вопрос нужной сложности
        question = Question.where(level: level).order('RANDOM()').first

        # Перемешиваем ответы — цисла от 1 до 4
        answers = [1, 2, 3, 4].shuffle

        # Наконец, создаем нужный объект GameQuestion и цепляем его к игре
        game.game_questions.create!(
          question: question,
          a: answers.pop, b: answers.pop, c: answers.pop, d: answers.pop
        )
      end

      # Возвращаем игру
      game
    end
  end

  # Метод current_game_question возвращает текущий, еще неотвеченный вопрос игры
  def current_game_question
    game_questions.detect { |q| q.question.level == current_level }
  end
  # added by Anikram
  def previous_game_question
    game_questions.detect { |q| q.question.level == previous_level }
  end

  # Метод previous_level возвращает число, равное предыдущему уровню сложности.
  # Обратите внимание, что этот метод возвращает -1 для новой игры.
  def previous_level
    current_level - 1
  end

  # Метод, который сообщает, закончена ли текущая игра. Возвращает true, если
  # у игры прописано поле :finished_at — время конца игры.
  def finished?
    finished_at.present?
  end

  # Метод time_out! проверяет текущее время и грохает игру + возвращает true
  # если время прошло.
  def time_out!
    if (Time.now - created_at) > TIME_LIMIT
      finish_game!(fire_proof_prize(previous_level), true)
      true
    end
  end

  # Основные игровые методы:

  # Метод answer_current_question возвращает
  #
  # * true, если ответ верный: текущая игра при этом обновляет свое состояние:
  #   меняется :current_level, :prize (если несгораемый уровень), поля
  #   :updated_at прописывается :finished_at если это был последний вопрос.
  #
  # * false, если 1) ответ неверный 2) время вышло 3) игра уже закончена ранее.
  #   В любом случае прописывается :finished_at, :prize (если несгораемый
  #   уровень), :updated_at.
  #
  # В качестве параметра letter в метод необходимо передать строку 'a','b','c'
  # или 'd'.
  def answer_current_question!(letter)
    # Законченную игру низя обновлять
    return false if time_out! || finished?

    # С помощью метода answer_correct? у текущего игрового вопроса проверяем,
    # правильно ли ответили на текущий вопрос.
    if current_game_question.answer_correct?(letter)
      # Если ответили правильно, увеличиваем текущий уровень вопроса.
      self.current_level += 1

      if current_level == Question::QUESTION_LEVELS.max + 1
        # Если это был последний вопрос, заканчиваем игру методом finish_game!
        finish_game!(PRIZES[Question::QUESTION_LEVELS.max], false)
      else
        # Если нет, сохраняем игру и идем дальше
        save!
      end

      # Возвращаем true, если ответ был правильным
      true
    else
      # Если ответили неправильно, заканчиваем игру методом finish_game! и
      # возвращаем false.
      finish_game!(fire_proof_prize(previous_level), true)
      false
    end
  end

  # Метод take_money! записывает юзеру игровую сумму на счет и завершает игру,
  def take_money!
    # Из законченной или неначатой игры нечего брать
    return if time_out! || finished?

    # Заканчиваем игру, записав игроку приз из несгораемых сумм
    finish_game!(previous_level > -1 ? PRIZES[previous_level] : 0, false)
  end

  # todo: дорогой ученик!
  # Код метода ниже можно сократиь в 3 раза с помощью возможностей Ruby и Rails,
  # подумайте как и реализуйте. Помните о безопасности и входных данных!
  #
  # Вариант решения вы найдете в комментарии в конце файла, отвечающего за настройки
  # хранения сессий вашего приложения. Вот такой вот вам ребус :)

  # Создает варианты подсказок для текущего игрового вопроса.
  # Возвращает true, если подсказка применилась успешно,
  # false если подсказка уже заюзана.
  #
  # help_type = :fifty_fifty | :audience_help | :friend_call
  def use_help(help_type)
    case help_type
    when :fifty_fifty
      unless fifty_fifty_user
        # ActiveRecord метод toggle! переключает булевое поле сразу в базе
        toggle!(:fifty_fifty_user)
        current_game_question.add_fifty_fifty
        return true
      end
    when :audience_help
      unless audience_help_used
        toggle!(:audience_help_used)
        current_game_question.add_audience_help
        return true
      end
    when :friend_call
      unless friend_call_used
        toggle!(:friend_call_used)
        current_game_question.add_friend_call
        return true
      end
    end

    false
  end

  # Результат игры status, возвращает, одно из:
  #
  # :fail — игра проиграна из-за неверного вопроса
  # :timeout — игра проиграна из-за таймаута
  # :won — игра выиграна (все 15 вопросов покорены)
  # :money — игра завершена, игрок забрал деньги
  # :in_progress — игра еще идет
  def status
    return :in_progress unless finished?

    if is_failed
      # TODO: дорогой ученик! Если TIME_LIMIT в будущем изменится, статусы
      # старых, уже сыгранных игр могут измениться. Подумайте как это исправить!
      # Ответ найдете в файле настроек вашего тестового окружения.
      (finished_at - created_at) > TIME_LIMIT ? :timeout : :fail
    elsif current_level > Question::QUESTION_LEVELS.max
      :won
    else
      :money
    end
  end

  private

  # Метод finish_game! завершает игру. Он обновляет все нужные поля и начисляет
  # юзеру выигрыш.
  def finish_game!(amount = 0, failed = true)
    # Оборачиваем в транзакцию — игра заканчивается и баланс юзера пополняется
    # только вместе.
    transaction do
      self.prize = amount
      self.finished_at = Time.now
      self.is_failed = failed
      user.balance += amount
      save!
      user.save!
    end
  end

  # Метод fire_proof_prize по заданному уровню вопроса вычисляет вознаграждение
  # за ближайшую несгораемую сумму.
  def fire_proof_prize(answered_level)
    level = FIREPROOF_LEVELS.select { |x| x <= answered_level }.last
    level.present? ? PRIZES[level] : 0
  end
end

app/controllers/games_controller.rb
# (c) goodprogrammer.ru
#
# Основной игровой контроллер
# Создает новую игру, обновляет статус игры по ответам юзера, выдает подсказки
class GamesController < ApplicationController
  before_action :authenticate_user!

  # Проверка нет ли у залогиненного юзера начатой игры
  before_action :goto_game_in_progress!, only: [:create]

  # Загружаем игру из базы для текущего юзера
  before_action :set_game, except: [:create]

  # Проверка — если игра завершена, отправляем юзера на его профиль, где он
  # может увидеть статистику сыгранных игр.
  before_action :redirect_from_finished_game!, except: [:create]

  def show
    @game_question = @game.current_game_question
  end

  # Действие create создает новую игру и отправляет на действие show (основной
  # игровой экран) в случае успеха.
  def create
    begin
      # Создаем игру для залогиненного юзера
      @game = Game.create_game_for_user!(current_user)

      # Отправляемся на страницу игры
      redirect_to game_path(@game), notice: I18n.t(
        'controllers.games.game_created',
        created_at: @game.created_at
      )
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved => ex
      # Если ошибка создания игры
      Rails.logger.error("Error creating game for user #{current_user.id}, " \
                         "msg = #{ex}. #{ex.backtrace}")

      # Отправляемся назад с алертом
      redirect_to :back, alert: I18n.t('controllers.games.game_not_created')
    end
  end

  # Действие answer принимает ответ на вопрос, единственный обязательный
  # параметр — params[:letter] — буква, которую выбрал игрок.
  def answer
    # Выясняем у игры, правильно ли оветили
    @answer_is_correct = @game.answer_current_question!(params[:letter])
    @game_question = @game.current_game_question

    unless @answer_is_correct
      # Если ответили неправильно, отправляем юзера на профиль с сообщением
      flash[:alert] = I18n.t(
        'controllers.games.bad_answer',
        answer: @game_question.correct_answer,
        prize: view_context.number_to_currency(@game.prize)
      )
    end

    respond_to do |format|
      format.html do
        if @answer_is_correct && !@game.finished?
          redirect_to game_path(@game)
        else
          redirect_to user_path(current_user)
        end
      end

      format.js {}
    end
  end

  # Действие take_money вызывается из шаблона, когда пользователь берет кнопку
  # «Взять деньги». Параметров нет, т.к. вся необходимая информация есть в базе.
  def take_money
    # Заканчиваем игру
    @game.take_money!

    # Отправялем пользователя на профиль с сообщение о выигрыше
    redirect_to user_path(current_user), flash: {
      warning: I18n.t(
        'controllers.games.game_finished',
        prize: view_context.number_to_currency(@game.prize)
      )
    }
  end

  def help
    # используем помощь в игре и по результату задаем сообщение юзеру
    msg = if @game.use_help(params[:help_type].to_sym)
            {flash: {info: I18n.t('controllers.games.help_used')}}
          else
            {alert: I18n.t('controllers.games.help_not_used')}
          end

    redirect_to game_path(@game), msg
  end

  private

  def redirect_from_finished_game!
    if @game.finished?
      redirect_to user_path(current_user), alert: I18n.t(
        'controllers.games.game_closed',
        game_id: @game.id
      )
    end
  end

  def goto_game_in_progress!
    # Вот нам и пригодился наш scope in_progress из модели Game
    game_in_progress = current_user.games.in_progress.first

    unless game_in_progress.blank?
      redirect_to game_path(game_in_progress), alert: I18n.t(
        'controllers.games.game_not_finished'
      )
    end
  end

  def set_game
    @game = current_user.games.find_by(id: params[:id])

    if @game.blank?
      # Если у current_user нет игры - посылаем
      redirect_to root_path, alert: I18n.t(
        'controllers.games.not_your_game'
      )
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def game_label(game)
    if game.status == :in_progress && current_user == game.user
      link_to content_tag(:span, t("game_statuses.#{game.status}"), class: 'label'), game_path(game)
    else
      content_tag :span, t("game_statuses.#{game.status}"), class: 'label label-danger'
    end
  end
end

app/views/games/_game_question.html.erb
<% game = game_question.game %>
<% help = @game_question.help_hash %>

<div class="alert alert-info text-center">
  <%# Выводим вопрос %>
  <h2><%= @game_question.text %></h2>
</div>

<div class="row">
  <%# Выводим варианты ответов %>
  <% @game_question.variants.each do |letter, variant| %>

    <% if !help.key?(:fifty_fifty) || help[:fifty_fifty].include?(letter) %>

      <div class="col-md-6 buffer-top">
        <%= link_to content_tag(:span, letter.upcase, class: 'variant') + ": #{variant}",
                    answer_game_path(game, letter: letter),
                    method: :put,
                    remote: true,
                    class: 'btn btn-block btn-default btn-variant'
        %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/games/_help.html.erb
<div class="game-help-info">
  <% if help.key?(:friend_call) || help.key?(:audience_help) %>
    <div class="row buffer-top-lg">
      <div class="col-xs-12">
        <% if help.key?(:friend_call) %>
          <div class="alert alert-info text-center">
            <%= help[:friend_call] %>
          </div>
        <% end %>

        <% if help.key?(:audience_help) %>
          <p>Зрители считают: </p>
          <% help[:audience_help].sort.map do |key, value | %>
            <div class="progress">
              <div class="progress-bar progress-bar-danger" style="width: <%= value %>%;">
                <%= key.upcase %>: <%= value %>%
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>


<div class="game-help row buffer-top">
  <div class="col-sm-4">
    <% unless game.fifty_fifty_user? %>
    <%= link_to '50/50', help_game_path(game, help_type: :fifty_fifty),
        method: :put, class: 'btn btn-default btn-block btn-help' %>
    <% end %>
  </div>

  <div class="col-sm-4">
    <% unless game.friend_call_used? %>
    <%= link_to fa_icon('phone'), help_game_path(game, help_type: :friend_call),
        method: :put, class: 'btn btn-default btn-block btn-help' %>
    <% end %>
  </div>

  <div class="col-sm-4">
    <% unless game.audience_help_used? %>
    <%= link_to fa_icon('users'), help_game_path(game, help_type: :audience_help),
        method: :put, class: 'btn btn-default btn-block btn-help' %>
    <% end %>
  </div>
</div>

app/views/games/answer.js.erb
<% if @answer_is_correct && !@game.finished? %>
$('.game-question').html("<%= escape_javascript (
  render partial: 'game_question', object: @game_question
  ) %>")

current_prize = $('.game-prizes').find('.active').toggleClass('active');
current_prize.prev().toggleClass('active');

$('.game-help-info').hide();
<% else %>
  window.location.href = '<%= user_path(current_user) %>'
<% end %>

app/views/games/show.html.erb
<div class="row">
  <div class="col-sm-9 col-sm-push-3">
    <div class="text-center">
      <%= image_tag asset_path('logo.png'), class: 'game-logo buffer-bottom' %>
    </div>

    <div class="game-question">
      <%= render partial: 'game_question', object: @game_question %>
    </div>

    <div class="buffer-top-lg">
      <%= render partial: 'help', object: @game_question.help_hash, locals: {game: @game} %>
    </div>
  </div>


  <div class="col-sm-3 col-sm-pull-9">
    <ul class="list-group list-group-prizes game-prizes">
      <%# Выводим список выигрышей за каждый вопрос, отмечая несгораемые суммы %>
      <% Game::PRIZES.reverse.each_with_index do |prize, index| %>
        <li class="list-group-item text-center <%= 'active' if (14 - index == @game.current_level) %>">
          <%= fa_icon('diamond') if Game::FIREPROOF_LEVELS.include?(14 - index) %>
          <%= prize %>
        </li>
      <% end %>
    </ul>

    <%# Ссылка на выход из игры с деньгами %>
    <%= link_to 'Забрать выигрыш', take_money_game_path(@game), method: :put, class: 'btn btn-info btn-block' %>
  </div>
</div>